### ISSUE TITLE
devise_token_auth をやめて devise + devise-jwt による認証に変更する

### ISSUE THREAD

**Issue by tom0418** [tom0418/tasks_manager#31]
## 概要

devise_token_auth ではなく、devise + devise-jwt によるトークン認証に変更する

## やること

- [x] devise_token_auth をアンインストール
- [x] devise_token_auth の設定、ルーティング、メソッドなどを削除
- [x] users テーブルを devise のものに変更する
- [x] User モデルの修正
- [x] Model Spec の修正

## TODO
- devise 周りの設定を変更
- devise-jwt のインストール
- User モデルに jwt 用のカラムを追加
